version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static  
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload